#!/usr/bin/env bash
warn() {
	echo "$@" "at $file:$num" >&2
}

name_check() {
	grep -Exq '[a-zA-Z_][a-zA-Z0-9_-]{,30}' <<< "$name" \
	|| { warn "Illegal name $name"; return 1; }
}

id_check() {
	case "$id" in /*) read -r id <<< "$(stat -c "%$type" "$id")";; esac
	if [ "$id" == "-" ]; then
		unset id
	elif ((id == 65535 || id == 4294967295)); then
		warn "Placeholder ID $id used"
		return 1
	fi
}

groups_cant_have() {
	[ -n "$1" ] && [ "$1" != "-" ] && warn "Groups can't have a $1"
}

ifexists() {
	local file
	case "$1" in
		user)  file="/etc/passwd" ;;
		group) file="/etc/group"  ;;
	esac
	grep -q "^$2:" "$file"
}

process_dir() {
	[ -d "$1" ] || return
	find "$1" -maxdepth 1 -name '*.conf' | sort \
	| while read -r file; do
		num=0
		while read -r line; do
			((num += 1))
			grep -Eq '^#|^\s*$' <<< "$line" && continue
			grep "%" <<< "$line" && warn "Specifiers are not implemented" && continue
			IFS=$'\n' read -rd '' type name id desc home shell <<< "$(
				tr ' ' '\n' <<< "$line" | awk '
					/^"/ {field = 1}
					/"$/ {field = 0}
					{if(field) {printf $0 " "} else {print}}
				'
			)"
			desc="${desc#\"}"
			desc="${desc%\"}"

			case "$type" in
				u)
					ifexists user "$name" && continue

					IFS=":" read -r id group <<< "$id"

					# shellcheck disable=SC2015
					name_check && id_check || continue

					[ "$desc" == "-" ] && unset desc
					grep -q ":" <<< "$desc" && warn "Description can't contain :" && continue

					[ "$home" == "-" ] && unset home
					: "${home:=/}"

					[ -n "$id" ] && ((id == 0)) && : "${shell:=/bin/sh}"
					: "${shell:=/usr/bin/nologin}"

					# we have name, home, shell
					# possibly missing: id, group, desc

					cmd=(useradd -r -d "$home" -s "$shell")
					[ -n "$id" ] && cmd+=(-u "$id")
					[ -n "$group" ] && cmd+=(-g "$group")
					[ -n "$desc" ] && cmd+=(-c "$desc")
					ifexists group "$name" && cmd+=(-g "$name")
					cmd+=("$name")

					echo "${cmd[*]}"
					"${cmd[@]}"
					;;
				g)
					ifexists group "$name" && continue

					# shellcheck disable=SC2015
					name_check && id_check || continue

					groups_cant_have "$desc" && continue
					groups_cant_have "$home" && continue
					groups_cant_have "$shell" && continue

					# we have: name
					# possibly missing: id

					cmd=(groupadd -r)
					[ -n "$id" ] && cmd+=(-g "$id")
					cmd+=("$name")

					"${cmd[@]}"
					;;
				m)
					grep -q "^$id:[^:]*:[^:]*:.*$name" "/etc/group" && continue
					usermod -a -G "$id" "$name"
					;;
				r) warn "Type $type not implemented" ;;
				*) warn "Unknown type $type" ;;
			esac
		done < "$file"
	done
}

for d in /etc/sysusers.d /run/sysusers.d /usr/lib/sysusers.d; do
	[ -d "$d" ] && process_dir "$d"
done
